### ISSUE TITLE
Proposed solution for eliminating boilerplate code in AutoEquatableEnum with associated values

### ISSUE THREAD

**Issue by cprovatas** [Rivukis/AutoEquatable#1]
```
import UIKit

protocol AutoEquatableEnum {
    static func == (lhs: Self, rhs: Self) -> Bool
}

extension AutoEquatableEnum {
    static func == (lhs: Self, rhs: Self) -> Bool {
        return lhs.data == rhs.data
    }
    
    private var data: NSData {
        var copy = self
        return withUnsafePointer(to: &copy, { NSData(bytes: $0, length: MemoryLayout<Self>.size) })
    }
}

enum Test: AutoEquatableEnum {
    case foo(String)
    case bar(String)
}

Test.foo("bar") == Test.foo("bar") // true
Test.foo("bar") == Test.bar("bar") // false
Test.bar("foo") == Test.bar("foo") // true
Test.bar("foo") == Test.bar("") // false
```

I have a solution that seems to work well for testing equatable between associated value enums without implementing any boilerplate across different enum types.

Advantages:
 - Significantly less code that has to be generated for each type
 - If an associated value is a custom object, this prevents that object from having to conform to AutoEquatable as well.

Please let me know your thoughts if you think this may be a plausible solution!

Thank you

Best Regards,

**Comment by Rivukis** [comment]
Hi Charlton Provatas,
Sorry, it took me so long to get back to you. I'll be honest and didn't see you proposed this. Thank you, for this solution. I might try to modify it so that only the enum case is using this approach and the associated values are required to use AutoEquatable. I like the idea that every type is treated the same, which is why I like your solution for enums and why I want to enforce AutoEquatable for associated values. Let me know your thoughts. Also, if you want to make a pull request that would be great. Otherwise I will poc, test and implement your idea when I get a chance.

Thanks again,
Brian Radebaugh

**Comment by Rivukis** [comment]
I've pushed out a new update (version 2.0) which now handles enums. I've decided to only use the convert to data trick to determine the enum case. I'm using AutoEquatable to check associated values so that it behaves like any other type conforming to AutoEquatable. I've also changed it to use `Data` instead of`NSData`. Let me know what you think and thank you for your help solving this issue!

**Comment by cprovatas** [comment]
@Rivukis Forgot to turn on notifications for this.  Thanks for implementing this and I'm glad it was of some help :)
